services:
  donation-agent-evaluator-service:
    image: ghcr.io/giveth/donation-agent-evaluator-service:staging
    container_name: donation-agent-evaluator-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PGSSLROOTCERT: /usr/src/app/db-ca.crt
      DATABASE_SSL_REJECT_UNAUTHORIZED: 'true'
    volumes:
      - ./db-ca.crt:/usr/src/app/db-ca.crt:ro
    ports:
      - '3001:3000'
    networks:
      - agent-distribution-service
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  agent-distribution-service:
    external: true
