services:
  donation-agent-evaluator-service:
    image: ghcr.io/giveth/donation-agent-evaluator-service:staging
    container_name: donation-agent-evaluator-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - "3001:3000"
    networks:
      - agent-distribution-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  agent-distribution-service:
    external: true

